#workflow name
name: CI

#workflow 시작될 조건
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest #실행환경 지정
    #실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '22'

      - name: Create application-secret.yml
        run: |
          echo "spring:" > src/main/resources/application-secret.yml
          echo "  security:" >> src/main/resources/application-secret.yml
          echo "    oauth2:" >> src/main/resources/application-secret.yml
          echo "      client:" >> src/main/resources/application-secret.yml
          echo "        registration:" >> src/main/resources/application-secret.yml
          echo "          google:" >> src/main/resources/application-secret.yml
          echo "            client-id: ${{ secrets.GOOGLE_CLIENT_ID }}" >> src/main/resources/application-secret.yml
          echo "            client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> src/main/resources/application-secret.yml
          echo "            scope:" >> src/main/resources/application-secret.yml
          echo "              - email" >> src/main/resources/application-secret.yml
          echo "              - profile" >> src/main/resources/application-secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build