#workflow name
name: CI/CD

#workflow 시작될 조건
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest #실행환경 지정
    #실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '22'

      - name: Create application-secret.yml
        run: |
          echo "spring:" > src/main/resources/application-secret.yml
          echo "  security:" >> src/main/resources/application-secret.yml
          echo "    oauth2:" >> src/main/resources/application-secret.yml
          echo "      client:" >> src/main/resources/application-secret.yml
          echo "        registration:" >> src/main/resources/application-secret.yml
          echo "          google:" >> src/main/resources/application-secret.yml
          echo "            client-id: ${{ secrets.GOOGLE_CLIENT_ID }}" >> src/main/resources/application-secret.yml
          echo "            client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> src/main/resources/application-secret.yml
          echo "            scope:" >> src/main/resources/application-secret.yml
          echo "              - email" >> src/main/resources/application-secret.yml
          echo "              - profile" >> src/main/resources/application-secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      #현재 시간 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      #배포용 패키지 경로 저장
      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV

      #빈스토크 배포
      - name: Beanstak Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: springboot-developer
          environment_name: Springboot-developer-env
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ./build/libs/${{env.artifact}}